coverage:
  status:
    project:
      default:
        target: auto  # auto compares coverage to the previous base commit

coverage:
  status:
    patch:
      default:
        target: 85%
        informational: true
    project:
      default:
        target: 65%
        threshold: 1%
        informational: true

comment:
  require_head: false     # default true
  require_base: false
  layout: "condensed_header, files, condensed_footer" # remove "new" from "header" and "footer"
  hide_project_coverage: false # set to false
  behavior: new