coverage:
  status:
    project:
      default:
        target: auto  # auto compares coverage to the previous base commit
comment:
  require_changes: true

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%