coverage:
  status:
    project:
      default:
        target: auto  # auto compares coverage to the previous base commit

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%

comment:
  layout: "header, files, footer" # remove "new" from "header" and "footer"
  hide_project_coverage: false # set to false