coverage:
  status:
    project:
      default:
        target: auto  # auto compares coverage to the previous base commit

coverage:
  status:
    patch:
      default:
        target: 0%
    project:
      default:
        target: 60%
        threshold: 1%

comment:
  require_head: false     # default true
  require_base: false
  layout: "header, files, footer" # remove "new" from "header" and "footer"
  hide_project_coverage: false # set to false
  behavior: new